Repository cloud-native-toolkit/terraform-tools-openshift-cicd, pull requests merged in 2022-05, with the labels that each got.

#52 Updates cloud-native-toolkit/terraform-tools-argocd module to v2.18.14
  main.tf
Labels: bug, minor

#60 Updates workflows to send notifications to discord
  .github/workflows/scheduled-verify.yaml
  .github/workflows/verify-pr.yaml
  .github/workflows/verify-workflow.yaml
  .github/workflows/verify.yaml
Labels: chore, patch

#61 Updates cloud-native-toolkit/terraform-tools-argocd module to v2.19.1
  main.tf
Labels: bug, patch

#62 Updates workflow publishing to discord
  .github/workflows/scheduled-verify.yaml
  .github/workflows/verify-workflow.yaml
Labels: chore, patch

#65 Updates tekton submodule and adds interface to module.yaml
  main.tf
  module.yaml
  outputs.tf
Labels: chore, patch

#64 Updates cloud-native-toolkit/terraform-tools-tekton module to v2.5.3
  main.tf
Labels: bug, minor
